mdp.core.State Class Reference
This class contains the source code for the State bean and Util methods.
Public Member Functions
State (String label, LinkedHashMap< String, Transition > transitions, float initialProbability)
This is a partial paraterized constructor of the State class.
State (String label, LinkedHashMap< String, Transition > transitions, float initialProbability, LinkedHashMap< String, Action > actionCounts, String regionLabel, String kernelLabel)
This is a complete paraterized constructor of the State class.
State (String label)
This is a default constructor of the State class.
State (State state)
This is a copy constructor of the State class that creates a deep copy of the argument State.
String getLabel ()
This method is a getter for the State label.
void setLabel (String label)
This method is a setter for the State label.
String getRegionLabel ()
This method is a getter for the Region Label to which the State belongs.
void setRegionLabel (String regionLabel)
This method is a setter for the Region Label to which the State belongs.
String getKernelLabel ()
This method is a getter for the Kernel Label to which the State belongs.
void setKernelLabel (String kernelLabel)
This method is a setter for the Kernel Label to which the State belongs.
Map< String, Transition > getTransitions ()
This method is a getter for the Transition that start from this State.
void setTransitions (LinkedHashMap< String, Transition > transitions)
This method is a setter for the Transition that start from this State.
float getInitialProbability ()
This method checks if this State is the initial state of the MDP.
void setInital (float initialProbability)
This method sets this State as the initial state of the MDP.
Map< String, Action > getActionCounts ()
This method returns the map of Key=action and Value=number of Transition with that action.
void setActionCounts (LinkedHashMap< String, Action > actionCounts)
This method sets the map of Key=action and Value=number of Transition with that action.
Transition addTransition (Transition t)
This method adds a Transition to the Transition Map of this State.
TreeSet< String > getNextStates ()
This is a default constructor of the MDP class.
String printActionCount ()
This method is used to print the data structure that holds the action counts.
String toString ()
This method converts the State object to a String for displaying on the console/GUI.
int hashCode ()
This method is used to compare two State objects.
boolean equals (Object obj)
This method is used to check if two State objects are equal or not.
Private Attributes
String label
LinkedHashMap< String, Transition > transitions
float initialProbability
LinkedHashMap< String, Action > actionCounts
String regionLabel
String kernelLabel
Detailed Description
This class contains the source code for the State bean and Util methods.
Definition at line 26 of file State.java.
Constructor & Destructor Documentation
mdp.core.State.State (String label, LinkedHashMap< String, Transition > transitions, float initialProbability)
This is a partial paraterized constructor of the State class.
Definition at line 38 of file State.java.
References mdp.core.State.initialProbability, mdp.core.State.label, and mdp.core.State.transitions.
Referenced by mdp.core.State.equals().
mdp.core.State.State (String label, LinkedHashMap< String, Transition > transitions, float initialProbability, LinkedHashMap< String, Action > actionCounts, String regionLabel, String kernelLabel)
This is a complete paraterized constructor of the State class.
Definition at line 52 of file State.java.
References mdp.core.State.actionCounts, mdp.core.State.initialProbability, mdp.core.State.kernelLabel, mdp.core.State.label, mdp.core.State.regionLabel, and mdp.core.State.transitions.
mdp.core.State.State (String label)
This is a default constructor of the State class.
Definition at line 66 of file State.java.
References mdp.core.State.label.
mdp.core.State.State (State state)
This is a copy constructor of the State class that creates a deep copy of the argument State.
Definition at line 80 of file State.java.
References mdp.core.State.actionCounts, mdp.core.State.initialProbability, mdp.core.State.kernelLabel, mdp.core.State.label, mdp.core.State.regionLabel, and mdp.core.State.transitions.
Member Function Documentation
Transition mdp.core.State.addTransition (Transition t)
This method adds a Transition to the Transition Map of this State.
Definition at line 182 of file State.java.
References mdp.core.Transition.toString().
boolean mdp.core.State.equals (Object obj)
This method is used to check if two State objects are equal or not.
Definition at line 295 of file State.java.
References mdp.core.State.actionCounts, mdp.core.State.initialProbability, mdp.core.State.kernelLabel, mdp.core.State.label, mdp.core.State.regionLabel, mdp.core.State.State(), and mdp.core.State.transitions.
Map<String, Action> mdp.core.State.getActionCounts ()
This method returns the map of Key=action and Value=number of Transition with that action.
Definition at line 168 of file State.java.
References mdp.core.State.actionCounts.
Referenced by mdp.core.MDP.buildFromFile(), and mdp.core.MDP.createXBCVector().
float mdp.core.State.getInitialProbability ()
This method checks if this State is the initial state of the MDP.
Definition at line 152 of file State.java.
References mdp.core.State.initialProbability.
Referenced by mdp.core.MDP.createXBCVector().
String mdp.core.State.getKernelLabel ()
This method is a getter for the Kernel Label to which the State belongs.
Definition at line 124 of file State.java.
References mdp.core.State.kernelLabel.
String mdp.core.State.getLabel ()
This method is a getter for the State label.
Definition at line 94 of file State.java.
References mdp.core.State.label.
Referenced by mdp.core.MDP.addState(), mdp.core.MDP.buildFromFile(), mdp.util.PlanarSeparator.DFSDecompositionIterative(), and mdp.util.PlanarSeparator.improveDecomposition().
TreeSet<String> mdp.core.State.getNextStates ()
This is a default constructor of the MDP class.
Definition at line 234 of file State.java.
Referenced by mdp.util.PlanarSeparator.DFSDecomposition(), and mdp.util.PlanarSeparator.DFSDecompositionIterative().
String mdp.core.State.getRegionLabel ()
This method is a getter for the Region Label to which the State belongs.
Definition at line 110 of file State.java.
References mdp.core.State.regionLabel.
Referenced by mdp.util.PlanarSeparator.improveDecomposition().
Map<String, Transition> mdp.core.State.getTransitions ()
This method is a getter for the Transition that start from this State.
Definition at line 138 of file State.java.
References mdp.core.State.transitions.
Referenced by mdp.core.MDP.buildFromFile(), mdp.core.MDP.createKernels(), and mdp.util.PlanarSeparator.improveDecomposition().
int mdp.core.State.hashCode ()
This method is used to compare two State objects.
Definition at line 274 of file State.java.
String mdp.core.State.printActionCount ()
This method is used to print the data structure that holds the action counts.
Definition at line 250 of file State.java.
Referenced by mdp.core.State.toString().
void mdp.core.State.setActionCounts (LinkedHashMap< String, Action > actionCounts)
This method sets the map of Key=action and Value=number of Transition with that action.
Definition at line 175 of file State.java.
References mdp.core.State.actionCounts.
void mdp.core.State.setInital (float initialProbability)
This method sets this State as the initial state of the MDP.
Definition at line 160 of file State.java.
References mdp.core.State.initialProbability.
void mdp.core.State.setKernelLabel (String kernelLabel)
This method is a setter for the Kernel Label to which the State belongs.
Definition at line 131 of file State.java.
References mdp.core.State.kernelLabel.
Referenced by mdp.util.PlanarSeparator.DFSDecomposition(), and mdp.util.PlanarSeparator.DFSDecompositionIterative().
void mdp.core.State.setLabel (String label)
This method is a setter for the State label.
Definition at line 102 of file State.java.
References mdp.core.State.label.
void mdp.core.State.setRegionLabel (String regionLabel)
This method is a setter for the Region Label to which the State belongs.
Definition at line 117 of file State.java.
References mdp.core.State.regionLabel.
Referenced by mdp.util.PlanarSeparator.DFSDecomposition(), and mdp.util.PlanarSeparator.DFSDecompositionIterative().
void mdp.core.State.setTransitions (LinkedHashMap< String, Transition > transitions)
This method is a setter for the Transition that start from this State.
Definition at line 145 of file State.java.
References mdp.core.State.transitions.
String mdp.core.State.toString ()
This method converts the State object to a String for displaying on the console/GUI.
Definition at line 265 of file State.java.
References mdp.core.State.printActionCount().
Member Data Documentation
LinkedHashMap<String, Action> mdp.core.State.actionCounts [private]
Definition at line 31 of file State.java.
Referenced by mdp.core.State.equals(), mdp.core.State.getActionCounts(), mdp.core.State.setActionCounts(), and mdp.core.State.State().
float mdp.core.State.initialProbability [private]
Definition at line 30 of file State.java.
Referenced by mdp.core.State.equals(), mdp.core.State.getInitialProbability(), mdp.core.State.setInital(), and mdp.core.State.State().
String mdp.core.State.kernelLabel [private]
Definition at line 33 of file State.java.
Referenced by mdp.core.State.equals(), mdp.core.State.getKernelLabel(), mdp.core.State.setKernelLabel(), and mdp.core.State.State().
String mdp.core.State.label [private]
Definition at line 28 of file State.java.
Referenced by mdp.core.State.equals(), mdp.core.State.getLabel(), mdp.core.State.setLabel(), and mdp.core.State.State().
String mdp.core.State.regionLabel [private]
Definition at line 32 of file State.java.
Referenced by mdp.core.State.equals(), mdp.core.State.getRegionLabel(), mdp.core.State.setRegionLabel(), and mdp.core.State.State().
LinkedHashMap<String, Transition> mdp.core.State.transitions [private]
Definition at line 29 of file State.java.
Referenced by mdp.core.State.equals(), mdp.core.State.getTransitions(), mdp.core.State.setTransitions(), and mdp.core.State.State().
The documentation for this class was generated from the following file:
src/mdp/core/State.java