ese.seas.upenn.edu.MDP Class Reference
This class contains the source code for the MDP bean and Util methods.
Public Member Functions
MDP ()
This is a default constructor of the MDP class.
MDP (MDP mdp)
This is a copy constructor of the MDP class that creates a new MDP object which is a deep copy of the first argument.
int getRegionCount ()
This method is a getter for the number of regions in the decomposition.
void setRegionCount (int regionCount)
This method is a setter for the number of regions in the decomposition.
float getGamma ()
This method is a getter for gamma variable.
Map< String, State > getStates ()
This method is a getter for states in the MDP.
void setStates (Map< String, State > states)
This method is a setter for states in the MDP.
Map< String, LinkedHashSet< String > > getRegions ()
This method is a getter for the regions in the decomposition of the MDP.
void setRegions (Map< String, LinkedHashSet< String >> regions)
This method is a setter for the regions in the decomposition of the MDP.
Map< String, LinkedHashSet< String > > getKernels ()
This method is a getter for the generated kernels in the decomposition of the MDP.
void setKernels (Map< String, LinkedHashSet< String >> kernels)
This method is a setter for the generated kernels in the decomposition of the MDP.
ArrayList< String > getActions ()
This method is a getter for the action set in the MDP.
void setActions (ArrayList< String > actions)
This method is a getter for the action set in the MDP.
SparseMatrixHolder getA ()
This method is a getter for the sparse matrix A used for the LP bsed solution of the MDP.
void setA (SparseMatrixHolder a)
This method is a setter for the sparse matrix A used for the LP bsed solution of the MDP.
State addState (State s)
This method adds the argument State s in the Map of States of the MDP.
void buildFromFile (String filename) throws Exception
This method is used to create an MDP object based a txt file.
void createLPQuick ()
This method is used to create A sparse matrix which is used to solve the MDP via LP.
int getStateActionPairCount (String kernel)
This method returns the number of integer count of the number of state-action pairs in a kernel.
void createAMatrix ()
This method converts the SparseMatrixHolder A into a .Mat file.
void createSparseAMatrix ()
This method converts the SparseMatrixHolder A into a .Mat file with sparse matrix representation used in MATLAB.
String toString ()
This method converts the MDP object into a String object for convinient displaying on the console/GUI.
Private Attributes
Map< String, State > states
Map< String, LinkedHashSet< String > > regions
Map< String, LinkedHashSet< String > > kernels
ArrayList< String > actions
SparseMatrixHolder A
final float gamma =(float)0.9
int regionCount
Detailed Description
This class contains the source code for the MDP bean and Util methods.
Definition at line 34 of file MDP.java.
Constructor & Destructor Documentation
ese.seas.upenn.edu.MDP.MDP ()
This is a default constructor of the MDP class.
Definition at line 47 of file MDP.java.
Referenced by ese.seas.upenn.edu.MDP.buildFromFile().
ese.seas.upenn.edu.MDP.MDP (MDP mdp)
This is a copy constructor of the MDP class that creates a new MDP object which is a deep copy of the first argument.
Definition at line 60 of file MDP.java.
References ese.seas.upenn.edu.MDP.actions, ese.seas.upenn.edu.MDP.kernels, ese.seas.upenn.edu.MDP.regionCount, ese.seas.upenn.edu.MDP.regions, and ese.seas.upenn.edu.MDP.states.
Member Function Documentation
State ese.seas.upenn.edu.MDP.addState (State s)
This method adds the argument State s in the Map of States of the MDP.
Definition at line 168 of file MDP.java.
References ese.seas.upenn.edu.State.getLabel().
void ese.seas.upenn.edu.MDP.buildFromFile (String filename) throws Exception
This method is used to create an MDP object based a txt file.
This method creates an MDP object by reading a txt file of the following format -
States of the MDP
 states {s0, s1}
Transitions in the MDP
 transitions
 {s0, a, 1, s1}
 {s1, b, 1, s0s}
 end
 Where each transition has the format - {fromState, action, probabilityOfTransition, ResultState}
Decomposition count
 Regions=2
Initially the txt file is parsed till the keyword States is encounterd. Then the Line is parsed to consctruct the states in the MDP.
 Then the file is parsed till the keyword Transitions is detected. Then onwards each new line is parsed to contruct a new transition and added to the Map of transitions of the state from which the transition begins. This continues till the keyword end is detected.
 Then the file is parsed till the keyword Regions is detected. This is used to denote the number of regions wanted in the MDP decomposition.
 Based on the above information, the MDP is the decomposed into regions via a DFS based interative algorithm.
 Further, based on the decomposition the MDP kernels are generated.
 At last the txt file is closed.
Definition at line 197 of file MDP.java.
References ese.seas.upenn.edu.State.getActionCounts(), ese.seas.upenn.edu.State.getLabel(), ese.seas.upenn.edu.PlanarSeparator.getLayers(), ese.seas.upenn.edu.State.getTransitions(), ese.seas.upenn.edu.PlanarSeparator.improveDecomposition(), ese.seas.upenn.edu.MDP.MDP(), ese.seas.upenn.edu.Transition.toString(), and ese.seas.upenn.edu.MDP.toString().
Referenced by ese.seas.upenn.edu.Main.main().
void ese.seas.upenn.edu.MDP.createAMatrix ()
This method converts the SparseMatrixHolder A into a .Mat file.
Definition at line 654 of file MDP.java.
References ese.seas.upenn.edu.SparseMatrixHolder.getMatrixHolder(), and ese.seas.upenn.edu.MDP.getStateActionPairCount().
void ese.seas.upenn.edu.MDP.createLPQuick ()
This method is used to create A sparse matrix which is used to solve the MDP via LP.
This method creates a SparseMatrixHolder to hold the A matrix for the LP of the MDP. The SparseMatrixHolder is created such that it has a map of maps, where each map contains the an Aij for every Ki and Kj if the resultant Aij is a non zero matrix.
 This method replaces createLP() method as an optimized method.
Definition at line 585 of file MDP.java.
References ese.seas.upenn.edu.State.getActionCounts(), and ese.seas.upenn.edu.SparseMatrixHolder.getMatrixHolder().
void ese.seas.upenn.edu.MDP.createSparseAMatrix ()
This method converts the SparseMatrixHolder A into a .Mat file with sparse matrix representation used in MATLAB.
Definition at line 697 of file MDP.java.
References ese.seas.upenn.edu.SparseMatrixHolder.getMatrixHolder(), and ese.seas.upenn.edu.MDP.getStateActionPairCount().
Referenced by ese.seas.upenn.edu.Main.main().
SparseMatrixHolder ese.seas.upenn.edu.MDP.getA ()
This method is a getter for the sparse matrix A used for the LP bsed solution of the MDP.
Definition at line 152 of file MDP.java.
References ese.seas.upenn.edu.MDP.A.
Referenced by ese.seas.upenn.edu.Main.main().
ArrayList<String> ese.seas.upenn.edu.MDP.getActions ()
This method is a getter for the action set in the MDP.
Definition at line 138 of file MDP.java.
References ese.seas.upenn.edu.MDP.actions.
float ese.seas.upenn.edu.MDP.getGamma ()
This method is a getter for gamma variable.
Definition at line 87 of file MDP.java.
References ese.seas.upenn.edu.MDP.gamma.
Map<String, LinkedHashSet<String> > ese.seas.upenn.edu.MDP.getKernels ()
This method is a getter for the generated kernels in the decomposition of the MDP.
Definition at line 124 of file MDP.java.
References ese.seas.upenn.edu.MDP.kernels.
int ese.seas.upenn.edu.MDP.getRegionCount ()
This method is a getter for the number of regions in the decomposition.
Definition at line 73 of file MDP.java.
References ese.seas.upenn.edu.MDP.regionCount.
Map<String, LinkedHashSet<String> > ese.seas.upenn.edu.MDP.getRegions ()
This method is a getter for the regions in the decomposition of the MDP.
Definition at line 110 of file MDP.java.
References ese.seas.upenn.edu.MDP.regions.
Referenced by ese.seas.upenn.edu.PlanarSeparator.improveDecomposition().
int ese.seas.upenn.edu.MDP.getStateActionPairCount (String kernel)
This method returns the number of integer count of the number of state-action pairs in a kernel.
Definition at line 640 of file MDP.java.
Referenced by ese.seas.upenn.edu.MDP.createAMatrix(), and ese.seas.upenn.edu.MDP.createSparseAMatrix().
Map<String, State> ese.seas.upenn.edu.MDP.getStates ()
This method is a getter for states in the MDP.
Definition at line 94 of file MDP.java.
References ese.seas.upenn.edu.MDP.states.
Referenced by ese.seas.upenn.edu.PlanarSeparator.improveDecomposition().
void ese.seas.upenn.edu.MDP.setA (SparseMatrixHolder a)
This method is a setter for the sparse matrix A used for the LP bsed solution of the MDP.
Definition at line 159 of file MDP.java.
void ese.seas.upenn.edu.MDP.setActions (ArrayList< String > actions)
This method is a getter for the action set in the MDP.
Definition at line 145 of file MDP.java.
References ese.seas.upenn.edu.MDP.actions.
void ese.seas.upenn.edu.MDP.setKernels (Map< String, LinkedHashSet< String >> kernels)
This method is a setter for the generated kernels in the decomposition of the MDP.
Definition at line 131 of file MDP.java.
References ese.seas.upenn.edu.MDP.kernels.
void ese.seas.upenn.edu.MDP.setRegionCount (int regionCount)
This method is a setter for the number of regions in the decomposition.
Definition at line 80 of file MDP.java.
References ese.seas.upenn.edu.MDP.regionCount.
void ese.seas.upenn.edu.MDP.setRegions (Map< String, LinkedHashSet< String >> regions)
This method is a setter for the regions in the decomposition of the MDP.
Definition at line 117 of file MDP.java.
References ese.seas.upenn.edu.MDP.regions.
void ese.seas.upenn.edu.MDP.setStates (Map< String, State > states)
This method is a setter for states in the MDP.
Definition at line 102 of file MDP.java.
References ese.seas.upenn.edu.MDP.states.
String ese.seas.upenn.edu.MDP.toString ()
This method converts the MDP object into a String object for convinient displaying on the console/GUI.
Definition at line 794 of file MDP.java.
References ese.seas.upenn.edu.MDP.actions.
Referenced by ese.seas.upenn.edu.MDP.buildFromFile().
Member Data Documentation
SparseMatrixHolder ese.seas.upenn.edu.MDP.A [private]
Definition at line 40 of file MDP.java.
Referenced by ese.seas.upenn.edu.MDP.getA().
ArrayList<String> ese.seas.upenn.edu.MDP.actions [private]
Definition at line 39 of file MDP.java.
Referenced by ese.seas.upenn.edu.MDP.getActions(), ese.seas.upenn.edu.MDP.MDP(), ese.seas.upenn.edu.MDP.setActions(), and ese.seas.upenn.edu.MDP.toString().
final float ese.seas.upenn.edu.MDP.gamma =(float)0.9 [private]
Definition at line 41 of file MDP.java.
Referenced by ese.seas.upenn.edu.MDP.getGamma().
Map<String, LinkedHashSet<String> > ese.seas.upenn.edu.MDP.kernels [private]
Definition at line 38 of file MDP.java.
Referenced by ese.seas.upenn.edu.MDP.getKernels(), ese.seas.upenn.edu.MDP.MDP(), and ese.seas.upenn.edu.MDP.setKernels().
int ese.seas.upenn.edu.MDP.regionCount [private]
Definition at line 42 of file MDP.java.
Referenced by ese.seas.upenn.edu.MDP.getRegionCount(), ese.seas.upenn.edu.MDP.MDP(), and ese.seas.upenn.edu.MDP.setRegionCount().
Map<String, LinkedHashSet<String> > ese.seas.upenn.edu.MDP.regions [private]
Definition at line 37 of file MDP.java.
Referenced by ese.seas.upenn.edu.MDP.getRegions(), ese.seas.upenn.edu.MDP.MDP(), and ese.seas.upenn.edu.MDP.setRegions().
Map<String, State> ese.seas.upenn.edu.MDP.states [private]
Definition at line 36 of file MDP.java.
Referenced by ese.seas.upenn.edu.MDP.getStates(), ese.seas.upenn.edu.MDP.MDP(), and ese.seas.upenn.edu.MDP.setStates().
The documentation for this class was generated from the following file:
src/ese/seas/upenn/edu/MDP.java