mdp.core.MDP Class Reference
This class contains the source code for the MDP bean and Util methods.
Public Member Functions
MDP ()
This is a default constructor of the MDP class.
MDP (MDP mdp)
This is a copy constructor of the MDP class that creates a new MDP object which is a deep copy of the first argument.
int getRegionCount ()
This method is a getter for the number of regions in the decomposition.
void setRegionCount (int regionCount)
This method is a setter for the number of regions in the decomposition.
float getGamma ()
This method is a getter for gamma variable.
Map< String, State > getStates ()
This method is a getter for states in the MDP.
void setStates (Map< String, State > states)
This method is a setter for states in the MDP.
Map< String, LinkedHashSet< String > > getRegions ()
This method is a getter for the regions in the decomposition of the MDP.
void setRegions (Map< String, LinkedHashSet< String >> regions)
This method is a setter for the regions in the decomposition of the MDP.
Map< String, LinkedHashSet< String > > getKernels ()
This method is a getter for the generated kernels in the decomposition of the MDP.
void setKernels (Map< String, LinkedHashSet< String >> kernels)
This method is a setter for the generated kernels in the decomposition of the MDP.
ArrayList< String > getActions ()
This method is a getter for the action set in the MDP.
void setActions (ArrayList< String > actions)
This method is a getter for the action set in the MDP.
SparseMatrixHolder getA ()
This method is a getter for the sparse matrix A used for the LP bsed solution of the MDP.
void setA (SparseMatrixHolder a)
This method is a setter for the sparse matrix A used for the LP bsed solution of the MDP.
Map< String, LinkedHashSet< String > > getxVector ()
void setxVector (Map< String, LinkedHashSet< String >> xVector)
Map< String, LinkedHashMap< String, Float > > getbVector ()
void setbVector (Map< String, LinkedHashMap< String, Float >> bVector)
Map< String, LinkedHashMap< String, Float > > getcVector ()
void setcVector (Map< String, LinkedHashMap< String, Float >> cVector)
State addState (State s)
This method adds the argument State s in the Map of States of the MDP.
void buildFromFile (String filename) throws Exception
This method is used to create an MDP object based a txt file.
void createKernels ()
This method creates Kernels based on the Decomposition of the MDP Kernels are created such that each region is associated with its own kernel and all the states that are in a region, by default become a part of the corresponding kernel
 But each state that has incoming transitions from any other region besides its own regions is removed from its original kernel and placed into a base kernel K0.
void createXBCVector ()
This is a cpoy constructor of the MDP class s.
void createLP ()
This method is used to create A sparse matrix which is used to solve the MDP via LP.
void createLPandMatrix ()
This method is used to create A sparse matrix and generates the MATLAB file A_B_C.mat which is used to solve the MDP via LP.
int getStateActionPairCount (String kernel)
This method returns the number of integer count of the number of state-action pairs in a kernel.
void createAMatrix ()
This method converts the SparseMatrixHolder A into a .Mat file.
void createSparseAMatrix ()
This method converts the SparseMatrixHolder A into a .Mat file with sparse matrix representation used in MATLAB.
String toString ()
This method converts the MDP object into a String object for convinient displaying on the console/GUI.
Private Attributes
Map< String, State > states
Map< String, LinkedHashSet< String > > regions
Map< String, LinkedHashSet< String > > kernels
ArrayList< String > actions
SparseMatrixHolder A
final float gamma =(float)0.9
int regionCount
Map< String, LinkedHashSet< String > > xVector
Map< String, LinkedHashMap< String, Float > > bVector
Map< String, LinkedHashMap< String, Float > > cVector
Detailed Description
This class contains the source code for the MDP bean and Util methods.
Definition at line 41 of file MDP.java.
Constructor & Destructor Documentation
mdp.core.MDP.MDP ()
This is a default constructor of the MDP class.
Definition at line 57 of file MDP.java.
Referenced by mdp.core.MDP.buildFromFile().
mdp.core.MDP.MDP (MDP mdp)
This is a copy constructor of the MDP class that creates a new MDP object which is a deep copy of the first argument.
Definition at line 73 of file MDP.java.
References mdp.core.MDP.actions, mdp.core.MDP.bVector, mdp.core.MDP.cVector, mdp.core.MDP.kernels, mdp.core.MDP.regionCount, mdp.core.MDP.regions, mdp.core.MDP.states, and mdp.core.MDP.xVector.
Member Function Documentation
State mdp.core.MDP.addState (State s)
This method adds the argument State s in the Map of States of the MDP.
Definition at line 204 of file MDP.java.
References mdp.core.State.getLabel().
void mdp.core.MDP.buildFromFile (String filename) throws Exception
This method is used to create an MDP object based a txt file.
This method creates an MDP object by reading a txt file of the following format -
States of the MDP
 states {s0, s1}
Transitions in the MDP
 transitions
 {s0, a, 1, s1}
 {s1, b, 1, s0s}
 end
 Where each transition has the format - {fromState, action, probabilityOfTransition, ResultState}
Decomposition count
 Regions=2
Initially the txt file is parsed till the keyword States is encounterd. Then the Line is parsed to consctruct the states in the MDP.
 Then the file is parsed till the keyword Transitions is detected. Then onwards each new line is parsed to contruct a new transition and added to the Map of transitions of the state from which the transition begins. This continues till the keyword end is detected.
 Then the file is parsed till the keyword Regions is detected. This is used to denote the number of regions wanted in the MDP decomposition.
 Based on the above information, the MDP is the decomposed into regions via a DFS based interative algorithm.
 Further, based on the decomposition the MDP kernels are generated.
 At last the txt file is closed.
Definition at line 235 of file MDP.java.
References mdp.core.MDP.createKernels(), mdp.core.MDP.createXBCVector(), mdp.util.PlanarSeparator.DFSDecompositionIterative(), mdp.core.State.getActionCounts(), mdp.core.State.getLabel(), mdp.util.PlanarSeparator.getLayers(), mdp.core.State.getTransitions(), mdp.util.PlanarSeparator.improveDecomposition(), mdp.util.PlanarSeparator.init(), mdp.core.MDP.MDP(), mdp.core.Action.setCount(), mdp.core.Transition.toString(), and mdp.core.MDP.toString().
Referenced by mdp.main.Main.main().
void mdp.core.MDP.createAMatrix ()
This method converts the SparseMatrixHolder A into a .Mat file.
Definition at line 988 of file MDP.java.
References mdp.util.SparseMatrixHolder.getMatrixHolder(), and mdp.core.MDP.getStateActionPairCount().
void mdp.core.MDP.createKernels ()
This method creates Kernels based on the Decomposition of the MDP Kernels are created such that each region is associated with its own kernel and all the states that are in a region, by default become a part of the corresponding kernel
 But each state that has incoming transitions from any other region besides its own regions is removed from its original kernel and placed into a base kernel K0.
Definition at line 536 of file MDP.java.
References mdp.core.State.getTransitions().
Referenced by mdp.core.MDP.buildFromFile().
void mdp.core.MDP.createLP ()
This method is used to create A sparse matrix which is used to solve the MDP via LP.
This method creates a SparseMatrixHolder to hold the A matrix for the LP of the MDP. The SparseMatrixHolder is created such that it has a map of maps, where each map contains the an Aij for every Ki and Kj if the resultant Aij is a non zero matrix.
NOTE - This method is currently not used.
Definition at line 693 of file MDP.java.
References mdp.core.State.getActionCounts(), and mdp.util.SparseMatrixHolder.getMatrixHolder().
void mdp.core.MDP.createLPandMatrix ()
This method is used to create A sparse matrix and generates the MATLAB file A_B_C.mat which is used to solve the MDP via LP.
This method creates a SparseMatrixHolder to hold the A matrix for the LP of the MDP. The SparseMatrixHolder is created such that it has a map of maps, where each map contains the an Aij for every Ki and Kj if the resultant Aij is a non zero matrix. Finally, the values of A SparseMatrixHolder and of B,C and X vectors are written into a .mat file.
Definition at line 776 of file MDP.java.
References mdp.core.MDP.bVector, mdp.core.MDP.cVector, mdp.core.State.getActionCounts(), and mdp.core.MDP.getStateActionPairCount().
Referenced by mdp.main.Main.main().
void mdp.core.MDP.createSparseAMatrix ()
This method converts the SparseMatrixHolder A into a .Mat file with sparse matrix representation used in MATLAB.
Definition at line 1031 of file MDP.java.
References mdp.core.MDP.bVector, mdp.core.MDP.cVector, mdp.util.SparseMatrixHolder.getMatrixHolder(), and mdp.core.MDP.getStateActionPairCount().
void mdp.core.MDP.createXBCVector ()
This is a cpoy constructor of the MDP class s.
This method is used to create X, B and C vectors in the MDP
This method creates a X, B and C vectors based on the ordering of the states and actions in the the MDP.
Definition at line 639 of file MDP.java.
References mdp.core.State.getActionCounts(), and mdp.core.State.getInitialProbability().
Referenced by mdp.core.MDP.buildFromFile().
SparseMatrixHolder mdp.core.MDP.getA ()
This method is a getter for the sparse matrix A used for the LP bsed solution of the MDP.
Definition at line 168 of file MDP.java.
References mdp.core.MDP.A.
ArrayList<String> mdp.core.MDP.getActions ()
This method is a getter for the action set in the MDP.
Definition at line 154 of file MDP.java.
References mdp.core.MDP.actions.
Map<String, LinkedHashMap<String, Float> > mdp.core.MDP.getbVector ()
Definition at line 185 of file MDP.java.
References mdp.core.MDP.bVector.
Map<String, LinkedHashMap<String, Float> > mdp.core.MDP.getcVector ()
Definition at line 191 of file MDP.java.
References mdp.core.MDP.cVector.
float mdp.core.MDP.getGamma ()
This method is a getter for gamma variable.
Definition at line 103 of file MDP.java.
References mdp.core.MDP.gamma.
Map<String, LinkedHashSet<String> > mdp.core.MDP.getKernels ()
This method is a getter for the generated kernels in the decomposition of the MDP.
Definition at line 140 of file MDP.java.
References mdp.core.MDP.kernels.
int mdp.core.MDP.getRegionCount ()
This method is a getter for the number of regions in the decomposition.
Definition at line 89 of file MDP.java.
References mdp.core.MDP.regionCount.
Referenced by mdp.util.PlanarSeparator.DFSDecomposition(), and mdp.util.PlanarSeparator.DFSDecompositionIterative().
Map<String, LinkedHashSet<String> > mdp.core.MDP.getRegions ()
This method is a getter for the regions in the decomposition of the MDP.
Definition at line 126 of file MDP.java.
References mdp.core.MDP.regions.
Referenced by mdp.util.PlanarSeparator.improveDecomposition().
int mdp.core.MDP.getStateActionPairCount (String kernel)
This method returns the number of integer count of the number of state-action pairs in a kernel.
Definition at line 974 of file MDP.java.
Referenced by mdp.core.MDP.createAMatrix(), mdp.core.MDP.createLPandMatrix(), and mdp.core.MDP.createSparseAMatrix().
Map<String, State> mdp.core.MDP.getStates ()
This method is a getter for states in the MDP.
Definition at line 110 of file MDP.java.
References mdp.core.MDP.states.
Referenced by mdp.util.PlanarSeparator.BFSLayerGeneration(), mdp.util.PlanarSeparator.DFSDecomposition(), mdp.util.PlanarSeparator.DFSDecompositionIterative(), and mdp.util.PlanarSeparator.improveDecomposition().
Map<String, LinkedHashSet<String> > mdp.core.MDP.getxVector ()
Definition at line 179 of file MDP.java.
References mdp.core.MDP.xVector.
void mdp.core.MDP.setA (SparseMatrixHolder a)
This method is a setter for the sparse matrix A used for the LP bsed solution of the MDP.
Definition at line 175 of file MDP.java.
void mdp.core.MDP.setActions (ArrayList< String > actions)
This method is a getter for the action set in the MDP.
Definition at line 161 of file MDP.java.
References mdp.core.MDP.actions.
void mdp.core.MDP.setbVector (Map< String, LinkedHashMap< String, Float >> bVector)
Definition at line 188 of file MDP.java.
References mdp.core.MDP.bVector.
void mdp.core.MDP.setcVector (Map< String, LinkedHashMap< String, Float >> cVector)
Definition at line 194 of file MDP.java.
References mdp.core.MDP.cVector.
void mdp.core.MDP.setKernels (Map< String, LinkedHashSet< String >> kernels)
This method is a setter for the generated kernels in the decomposition of the MDP.
Definition at line 147 of file MDP.java.
References mdp.core.MDP.kernels.
void mdp.core.MDP.setRegionCount (int regionCount)
This method is a setter for the number of regions in the decomposition.
Definition at line 96 of file MDP.java.
References mdp.core.MDP.regionCount.
void mdp.core.MDP.setRegions (Map< String, LinkedHashSet< String >> regions)
This method is a setter for the regions in the decomposition of the MDP.
Definition at line 133 of file MDP.java.
References mdp.core.MDP.regions.
void mdp.core.MDP.setStates (Map< String, State > states)
This method is a setter for states in the MDP.
Definition at line 118 of file MDP.java.
References mdp.core.MDP.states.
void mdp.core.MDP.setxVector (Map< String, LinkedHashSet< String >> xVector)
Definition at line 182 of file MDP.java.
References mdp.core.MDP.xVector.
String mdp.core.MDP.toString ()
This method converts the MDP object into a String object for convinient displaying on the console/GUI.
Definition at line 1179 of file MDP.java.
References mdp.core.MDP.actions.
Referenced by mdp.core.MDP.buildFromFile().
Member Data Documentation
SparseMatrixHolder mdp.core.MDP.A [private]
Definition at line 47 of file MDP.java.
Referenced by mdp.core.MDP.getA().
ArrayList<String> mdp.core.MDP.actions [private]
Definition at line 46 of file MDP.java.
Referenced by mdp.core.MDP.getActions(), mdp.core.MDP.MDP(), mdp.core.MDP.setActions(), and mdp.core.MDP.toString().
Map<String, LinkedHashMap<String,Float> > mdp.core.MDP.bVector [private]
Definition at line 51 of file MDP.java.
Referenced by mdp.core.MDP.createLPandMatrix(), mdp.core.MDP.createSparseAMatrix(), mdp.core.MDP.getbVector(), mdp.core.MDP.MDP(), and mdp.core.MDP.setbVector().
Map<String, LinkedHashMap<String,Float> > mdp.core.MDP.cVector [private]
Definition at line 52 of file MDP.java.
Referenced by mdp.core.MDP.createLPandMatrix(), mdp.core.MDP.createSparseAMatrix(), mdp.core.MDP.getcVector(), mdp.core.MDP.MDP(), and mdp.core.MDP.setcVector().
final float mdp.core.MDP.gamma =(float)0.9 [private]
Definition at line 48 of file MDP.java.
Referenced by mdp.core.MDP.getGamma().
Map<String, LinkedHashSet<String> > mdp.core.MDP.kernels [private]
Definition at line 45 of file MDP.java.
Referenced by mdp.core.MDP.getKernels(), mdp.core.MDP.MDP(), and mdp.core.MDP.setKernels().
int mdp.core.MDP.regionCount [private]
Definition at line 49 of file MDP.java.
Referenced by mdp.core.MDP.getRegionCount(), mdp.core.MDP.MDP(), and mdp.core.MDP.setRegionCount().
Map<String, LinkedHashSet<String> > mdp.core.MDP.regions [private]
Definition at line 44 of file MDP.java.
Referenced by mdp.core.MDP.getRegions(), mdp.core.MDP.MDP(), and mdp.core.MDP.setRegions().
Map<String, State> mdp.core.MDP.states [private]
Definition at line 43 of file MDP.java.
Referenced by mdp.core.MDP.getStates(), mdp.core.MDP.MDP(), and mdp.core.MDP.setStates().
Map<String, LinkedHashSet<String> > mdp.core.MDP.xVector [private]
Definition at line 50 of file MDP.java.
Referenced by mdp.core.MDP.getxVector(), mdp.core.MDP.MDP(), and mdp.core.MDP.setxVector().
The documentation for this class was generated from the following file:
src/mdp/core/MDP.java