ese.seas.upenn.edu.PlanarSeparator Class Reference
This class contains the source code for the BFS and DFS based MDP decomposition.
Static Public Member Functions
static HashSet< String > getSeenStates ()
This method is a getter for the seenState HashMap.
static void setSeenStates (HashSet< String > seenStates)
This method is a setter for the seenState HashMap.
static LinkedHashMap< String, LinkedHashSet< String > > getLayers ()
This method is a getter for the Layers HashMap that returns the resultant decompositon.
static void setLayers (LinkedHashMap< String, LinkedHashSet< String >> layers)
This method is a setter for the Layers HashMap.
static int getLayerCount ()
This method is a getter for the Layer Count.
static void setLayerCount (int layerCount)
This method is a setter for the Layer Count.
static Map< String, LinkedHashSet< String > > improveDecomposition (MDP mdp)
This method improves the basic DFS/BFS based decomposition of the given MDP.
Static Private Attributes
static HashSet< String > seenStates
static LinkedHashMap< String, LinkedHashSet< String > > layers
static int layerCount
Detailed Description
This class contains the source code for the BFS and DFS based MDP decomposition.
Definition at line 28 of file PlanarSeparator.java.
Member Function Documentation
static int ese.seas.upenn.edu.PlanarSeparator.getLayerCount () [static]
This method is a getter for the Layer Count.
Definition at line 65 of file PlanarSeparator.java.
References ese.seas.upenn.edu.PlanarSeparator.layerCount.
static LinkedHashMap<String, LinkedHashSet<String> > ese.seas.upenn.edu.PlanarSeparator.getLayers () [static]
This method is a getter for the Layers HashMap that returns the resultant decompositon.
Definition at line 51 of file PlanarSeparator.java.
References ese.seas.upenn.edu.PlanarSeparator.layers.
Referenced by ese.seas.upenn.edu.MDP.buildFromFile().
static HashSet<String> ese.seas.upenn.edu.PlanarSeparator.getSeenStates () [static]
This method is a getter for the seenState HashMap.
Definition at line 37 of file PlanarSeparator.java.
References ese.seas.upenn.edu.PlanarSeparator.seenStates.
static Map<String, LinkedHashSet<String> > ese.seas.upenn.edu.PlanarSeparator.improveDecomposition (MDP mdp) [static]
This method improves the basic DFS/BFS based decomposition of the given MDP.
This method improves the decomposition by using an heuristic that a State should belong to the Region To and From which it has the maximum number of Transition.
 The method goes through each State in the nested Map that contains Key=State and Value=Map of {Key = Region and Value = Count of Transition to and From that Region to that State}
 Then the resultant Map is checked to return the Dominant Region of every State and if the State does not belong to that Region then its Region is changed to that Region. Finally the resultant decomposition is returned to the calling method.
Definition at line 187 of file PlanarSeparator.java.
References ese.seas.upenn.edu.State.getLabel(), ese.seas.upenn.edu.State.getRegionLabel(), ese.seas.upenn.edu.MDP.getRegions(), ese.seas.upenn.edu.MDP.getStates(), and ese.seas.upenn.edu.State.getTransitions().
Referenced by ese.seas.upenn.edu.MDP.buildFromFile().
static void ese.seas.upenn.edu.PlanarSeparator.setLayerCount (int layerCount) [static]
This method is a setter for the Layer Count.
Definition at line 72 of file PlanarSeparator.java.
References ese.seas.upenn.edu.PlanarSeparator.layerCount.
static void ese.seas.upenn.edu.PlanarSeparator.setLayers (LinkedHashMap< String, LinkedHashSet< String >> layers) [static]
This method is a setter for the Layers HashMap.
Definition at line 58 of file PlanarSeparator.java.
References ese.seas.upenn.edu.PlanarSeparator.layers.
static void ese.seas.upenn.edu.PlanarSeparator.setSeenStates (HashSet< String > seenStates) [static]
This method is a setter for the seenState HashMap.
Definition at line 44 of file PlanarSeparator.java.
References ese.seas.upenn.edu.PlanarSeparator.seenStates.
Member Data Documentation
int ese.seas.upenn.edu.PlanarSeparator.layerCount [static], [private]
Definition at line 32 of file PlanarSeparator.java.
Referenced by ese.seas.upenn.edu.PlanarSeparator.getLayerCount(), and ese.seas.upenn.edu.PlanarSeparator.setLayerCount().
LinkedHashMap<String, LinkedHashSet<String> > ese.seas.upenn.edu.PlanarSeparator.layers [static], [private]
Definition at line 31 of file PlanarSeparator.java.
Referenced by ese.seas.upenn.edu.PlanarSeparator.getLayers(), and ese.seas.upenn.edu.PlanarSeparator.setLayers().
HashSet<String> ese.seas.upenn.edu.PlanarSeparator.seenStates [static], [private]
Definition at line 30 of file PlanarSeparator.java.
Referenced by ese.seas.upenn.edu.PlanarSeparator.getSeenStates(), and ese.seas.upenn.edu.PlanarSeparator.setSeenStates().
The documentation for this class was generated from the following file:
src/ese/seas/upenn/edu/PlanarSeparator.java