ese.seas.upenn.edu.State Class Reference
This class contains the source code for the State bean and Util methods.
Public Member Functions
State (String label, LinkedHashMap< String, Transition > transitions, boolean isInital)
This is a partial paraterized constructor of the State class.
State (String label, LinkedHashMap< String, Transition > transitions, boolean isInital, LinkedHashMap< String, Integer > actionCounts, String regionLabel, String kernelLabel)
This is a complete paraterized constructor of the State class.
State (String label)
This is a default constructor of the State class.
State (State state)
This is a copy constructor of the State class that creates a deep copy of the argument State.
String getLabel ()
This method is a getter for the State label.
void setLabel (String label)
This method is a setter for the State label.
String getRegionLabel ()
This method is a getter for the Region Label to which the State belongs.
void setRegionLabel (String regionLabel)
This method is a setter for the Region Label to which the State belongs.
String getKernelLabel ()
This method is a getter for the Kernel Label to which the State belongs.
void setKernelLabel (String kernelLabel)
This method is a setter for the Kernel Label to which the State belongs.
Map< String, Transition > getTransitions ()
This method is a getter for the Transition that start from this State.
void setTransitions (LinkedHashMap< String, Transition > transitions)
This method is a setter for the Transition that start from this State.
boolean isInital ()
This method checks if this State is the initial state of the MDP.
void setInital (boolean isInital)
This method sets this State as the initial state of the MDP.
Map< String, Integer > getActionCounts ()
This method returns the map of Key=action and Value=number of Transition with that action.
void setActionCounts (LinkedHashMap< String, Integer > actionCounts)
This method sets the map of Key=action and Value=number of Transition with that action.
Transition addTransition (Transition t)
This method adds a Transition to the Transition Map of this State.
String toString ()
This method converts the STate object to a String for displaying on the console/GUI.
int hashCode ()
This method is used to compare two State objects.
boolean equals (Object obj)
This method is used to check if two State objects are equal or not.
Private Attributes
String label
LinkedHashMap< String, Transition > transitions
boolean isInital
LinkedHashMap< String, Integer > actionCounts
String regionLabel
String kernelLabel
Detailed Description
This class contains the source code for the State bean and Util methods.
Definition at line 28 of file State.java.
Constructor & Destructor Documentation
ese.seas.upenn.edu.State.State (String label, LinkedHashMap< String, Transition > transitions, boolean isInital)
This is a partial paraterized constructor of the State class.
Definition at line 40 of file State.java.
References ese.seas.upenn.edu.State.isInital(), ese.seas.upenn.edu.State.label, and ese.seas.upenn.edu.State.transitions.
Referenced by ese.seas.upenn.edu.State.equals().
ese.seas.upenn.edu.State.State (String label, LinkedHashMap< String, Transition > transitions, boolean isInital, LinkedHashMap< String, Integer > actionCounts, String regionLabel, String kernelLabel)
This is a complete paraterized constructor of the State class.
Definition at line 54 of file State.java.
References ese.seas.upenn.edu.State.actionCounts, ese.seas.upenn.edu.State.isInital(), ese.seas.upenn.edu.State.kernelLabel, ese.seas.upenn.edu.State.label, ese.seas.upenn.edu.State.regionLabel, and ese.seas.upenn.edu.State.transitions.
ese.seas.upenn.edu.State.State (String label)
This is a default constructor of the State class.
Definition at line 68 of file State.java.
References ese.seas.upenn.edu.State.label.
ese.seas.upenn.edu.State.State (State state)
This is a copy constructor of the State class that creates a deep copy of the argument State.
Definition at line 82 of file State.java.
References ese.seas.upenn.edu.State.actionCounts, ese.seas.upenn.edu.State.isInital, ese.seas.upenn.edu.State.kernelLabel, ese.seas.upenn.edu.State.label, ese.seas.upenn.edu.State.regionLabel, and ese.seas.upenn.edu.State.transitions.
Member Function Documentation
Transition ese.seas.upenn.edu.State.addTransition (Transition t)
This method adds a Transition to the Transition Map of this State.
Definition at line 184 of file State.java.
References ese.seas.upenn.edu.Transition.toString().
boolean ese.seas.upenn.edu.State.equals (Object obj)
This method is used to check if two State objects are equal or not.
Definition at line 280 of file State.java.
References ese.seas.upenn.edu.State.actionCounts, ese.seas.upenn.edu.State.isInital, ese.seas.upenn.edu.State.label, ese.seas.upenn.edu.State.State(), and ese.seas.upenn.edu.State.transitions.
Map<String, Integer> ese.seas.upenn.edu.State.getActionCounts ()
This method returns the map of Key=action and Value=number of Transition with that action.
Definition at line 170 of file State.java.
References ese.seas.upenn.edu.State.actionCounts.
Referenced by ese.seas.upenn.edu.MDP.buildFromFile(), and ese.seas.upenn.edu.MDP.createLPQuick().
String ese.seas.upenn.edu.State.getKernelLabel ()
This method is a getter for the Kernel Label to which the State belongs.
Definition at line 126 of file State.java.
References ese.seas.upenn.edu.State.kernelLabel.
String ese.seas.upenn.edu.State.getLabel ()
This method is a getter for the State label.
Definition at line 96 of file State.java.
References ese.seas.upenn.edu.State.label.
Referenced by ese.seas.upenn.edu.MDP.addState(), ese.seas.upenn.edu.MDP.buildFromFile(), and ese.seas.upenn.edu.PlanarSeparator.improveDecomposition().
String ese.seas.upenn.edu.State.getRegionLabel ()
This method is a getter for the Region Label to which the State belongs.
Definition at line 112 of file State.java.
References ese.seas.upenn.edu.State.regionLabel.
Referenced by ese.seas.upenn.edu.PlanarSeparator.improveDecomposition().
Map<String, Transition> ese.seas.upenn.edu.State.getTransitions ()
This method is a getter for the Transition that start from this State.
Definition at line 140 of file State.java.
References ese.seas.upenn.edu.State.transitions.
Referenced by ese.seas.upenn.edu.MDP.buildFromFile(), and ese.seas.upenn.edu.PlanarSeparator.improveDecomposition().
int ese.seas.upenn.edu.State.hashCode ()
This method is used to compare two State objects.
Definition at line 263 of file State.java.
boolean ese.seas.upenn.edu.State.isInital ()
This method checks if this State is the initial state of the MDP.
Definition at line 154 of file State.java.
Referenced by ese.seas.upenn.edu.State.setInital(), and ese.seas.upenn.edu.State.State().
void ese.seas.upenn.edu.State.setActionCounts (LinkedHashMap< String, Integer > actionCounts)
This method sets the map of Key=action and Value=number of Transition with that action.
Definition at line 177 of file State.java.
References ese.seas.upenn.edu.State.actionCounts.
void ese.seas.upenn.edu.State.setInital (boolean isInital)
This method sets this State as the initial state of the MDP.
Definition at line 162 of file State.java.
References ese.seas.upenn.edu.State.isInital().
void ese.seas.upenn.edu.State.setKernelLabel (String kernelLabel)
This method is a setter for the Kernel Label to which the State belongs.
Definition at line 133 of file State.java.
References ese.seas.upenn.edu.State.kernelLabel.
void ese.seas.upenn.edu.State.setLabel (String label)
This method is a setter for the State label.
Definition at line 104 of file State.java.
References ese.seas.upenn.edu.State.label.
void ese.seas.upenn.edu.State.setRegionLabel (String regionLabel)
This method is a setter for the Region Label to which the State belongs.
Definition at line 119 of file State.java.
References ese.seas.upenn.edu.State.regionLabel.
void ese.seas.upenn.edu.State.setTransitions (LinkedHashMap< String, Transition > transitions)
This method is a setter for the Transition that start from this State.
Definition at line 147 of file State.java.
References ese.seas.upenn.edu.State.transitions.
String ese.seas.upenn.edu.State.toString ()
This method converts the STate object to a String for displaying on the console/GUI.
Definition at line 254 of file State.java.
Member Data Documentation
LinkedHashMap<String, Integer> ese.seas.upenn.edu.State.actionCounts [private]
Definition at line 33 of file State.java.
Referenced by ese.seas.upenn.edu.State.equals(), ese.seas.upenn.edu.State.getActionCounts(), ese.seas.upenn.edu.State.setActionCounts(), and ese.seas.upenn.edu.State.State().
boolean ese.seas.upenn.edu.State.isInital [private]
Definition at line 32 of file State.java.
Referenced by ese.seas.upenn.edu.State.equals(), and ese.seas.upenn.edu.State.State().
String ese.seas.upenn.edu.State.kernelLabel [private]
Definition at line 35 of file State.java.
Referenced by ese.seas.upenn.edu.State.getKernelLabel(), ese.seas.upenn.edu.State.setKernelLabel(), and ese.seas.upenn.edu.State.State().
String ese.seas.upenn.edu.State.label [private]
Definition at line 30 of file State.java.
Referenced by ese.seas.upenn.edu.State.equals(), ese.seas.upenn.edu.State.getLabel(), ese.seas.upenn.edu.State.setLabel(), and ese.seas.upenn.edu.State.State().
String ese.seas.upenn.edu.State.regionLabel [private]
Definition at line 34 of file State.java.
Referenced by ese.seas.upenn.edu.State.getRegionLabel(), ese.seas.upenn.edu.State.setRegionLabel(), and ese.seas.upenn.edu.State.State().
LinkedHashMap<String, Transition> ese.seas.upenn.edu.State.transitions [private]
Definition at line 31 of file State.java.
Referenced by ese.seas.upenn.edu.State.equals(), ese.seas.upenn.edu.State.getTransitions(), ese.seas.upenn.edu.State.setTransitions(), and ese.seas.upenn.edu.State.State().
The documentation for this class was generated from the following file:
src/ese/seas/upenn/edu/State.java