ese.seas.upenn.edu.SparseMatrixHolder Class Reference
This class contains the source code SparseMatrixHolder.
Public Member Functions
SparseMatrixHolder ()
This is the default constructor of SparseMatrixHolder class.
Map< String, LinkedHashMap< String, Float > > getMatrixHolder ()
This method is a getter for the matrixHolder HashMap.
void setMatrixHolder (Map< String, LinkedHashMap< String, Float >> matrixHolder)
This method is a setter for the matrixHolder HashMap.
String toString ()
This method converts the SparseMatrixHolder object into STring object for displaying on the console/GUI.
Private Attributes
Map< String, LinkedHashMap< String, Float > > matrixHolder
Detailed Description
This class contains the source code SparseMatrixHolder.
Definition at line 24 of file SparseMatrixHolder.java.
Constructor & Destructor Documentation
ese.seas.upenn.edu.SparseMatrixHolder.SparseMatrixHolder ()
This is the default constructor of SparseMatrixHolder class.
Definition at line 31 of file SparseMatrixHolder.java.
Member Function Documentation
Map<String, LinkedHashMap<String, Float> > ese.seas.upenn.edu.SparseMatrixHolder.getMatrixHolder ()
This method is a getter for the matrixHolder HashMap.
Definition at line 39 of file SparseMatrixHolder.java.
References ese.seas.upenn.edu.SparseMatrixHolder.matrixHolder.
Referenced by ese.seas.upenn.edu.MDP.createAMatrix(), ese.seas.upenn.edu.MDP.createLPQuick(), and ese.seas.upenn.edu.MDP.createSparseAMatrix().
void ese.seas.upenn.edu.SparseMatrixHolder.setMatrixHolder (Map< String, LinkedHashMap< String, Float >> matrixHolder)
This method is a setter for the matrixHolder HashMap.
Definition at line 46 of file SparseMatrixHolder.java.
References ese.seas.upenn.edu.SparseMatrixHolder.matrixHolder.
String ese.seas.upenn.edu.SparseMatrixHolder.toString ()
This method converts the SparseMatrixHolder object into STring object for displaying on the console/GUI.
Definition at line 54 of file SparseMatrixHolder.java.
Member Data Documentation
Map<String, LinkedHashMap<String, Float> > ese.seas.upenn.edu.SparseMatrixHolder.matrixHolder [private]
Definition at line 26 of file SparseMatrixHolder.java.
Referenced by ese.seas.upenn.edu.SparseMatrixHolder.getMatrixHolder(), and ese.seas.upenn.edu.SparseMatrixHolder.setMatrixHolder().
The documentation for this class was generated from the following file:
src/ese/seas/upenn/edu/SparseMatrixHolder.java