mdp.main.Main Class Reference
This class is used to create an MDP object from a text file and create a decomposition within that object and output the results i a .Mat file.
Static Public Member Functions
static void main (String[] args)
This method is used to create an MDP object from a text file and create a decomposition within that object and output the results i a .Mat file.
Detailed Description
This class is used to create an MDP object from a text file and create a decomposition within that object and output the results i a .Mat file.
Definition at line 49 of file Main.java.
Member Function Documentation
static void mdp.main.Main.main (String[] args) [static]
This method is used to create an MDP object from a text file and create a decomposition within that object and output the results i a .Mat file.
Definition at line 57 of file Main.java.
References mdp.core.MDP.buildFromFile(), mdp.core.MDP.createLP(), mdp.test.TestMDP.createMDP(), and mdp.core.MDP.createSparseAMatrix().
The documentation for this class was generated from the following file:
src/mdp/main/Main.java