mdp.util.SparseMatrixHolder Class Reference
This class contains the source code SparseMatrixHolder.
Public Member Functions
SparseMatrixHolder ()
This is the default constructor of SparseMatrixHolder class.
Map< String, LinkedHashMap< String, Float > > getMatrixHolder ()
This method is a getter for the matrixHolder HashMap.
void setMatrixHolder (Map< String, LinkedHashMap< String, Float >> matrixHolder)
This method is a setter for the matrixHolder HashMap.
String toString ()
This method converts the SparseMatrixHolder object into STring object for displaying on the console/GUI.
int getElementCount (int type)
Private Attributes
Map< String, LinkedHashMap< String, Float > > matrixHolder
Detailed Description
This class contains the source code SparseMatrixHolder.
Definition at line 24 of file SparseMatrixHolder.java.
Constructor & Destructor Documentation
mdp.util.SparseMatrixHolder.SparseMatrixHolder ()
This is the default constructor of SparseMatrixHolder class.
Definition at line 31 of file SparseMatrixHolder.java.
Member Function Documentation
int mdp.util.SparseMatrixHolder.getElementCount (int type)
Definition at line 68 of file SparseMatrixHolder.java.
Map<String, LinkedHashMap<String, Float> > mdp.util.SparseMatrixHolder.getMatrixHolder ()
This method is a getter for the matrixHolder HashMap.
Definition at line 39 of file SparseMatrixHolder.java.
References mdp.util.SparseMatrixHolder.matrixHolder.
Referenced by mdp.core.MDP.createAMatrix(), mdp.core.MDP.createLP(), and mdp.core.MDP.createSparseAMatrix().
void mdp.util.SparseMatrixHolder.setMatrixHolder (Map< String, LinkedHashMap< String, Float >> matrixHolder)
This method is a setter for the matrixHolder HashMap.
Definition at line 46 of file SparseMatrixHolder.java.
References mdp.util.SparseMatrixHolder.matrixHolder.
String mdp.util.SparseMatrixHolder.toString ()
This method converts the SparseMatrixHolder object into STring object for displaying on the console/GUI.
Definition at line 54 of file SparseMatrixHolder.java.
Member Data Documentation
Map<String, LinkedHashMap<String, Float> > mdp.util.SparseMatrixHolder.matrixHolder [private]
Definition at line 26 of file SparseMatrixHolder.java.
Referenced by mdp.util.SparseMatrixHolder.getMatrixHolder(), and mdp.util.SparseMatrixHolder.setMatrixHolder().
The documentation for this class was generated from the following file:
src/mdp/util/SparseMatrixHolder.java