mdp.util.PlanarSeparator Class Reference
This class contains the source code for the BFS and DFS based MDP decomposition.
Static Public Member Functions
static HashSet< String > getSeenStates ()
This method is a getter for the seenState HashMap.
static void setSeenStates (HashSet< String > seenStates)
This method is a setter for the seenState HashMap.
static LinkedHashMap< String, LinkedHashSet< String > > getLayers ()
This method is a getter for the Layers HashMap that returns the resultant decompositon.
static void setLayers (LinkedHashMap< String, LinkedHashSet< String >> layers)
This method is a setter for the Layers HashMap.
static int getLayerCount ()
This method is a getter for the Layer Count.
static void setLayerCount (int layerCount)
This method is a setter for the Layer Count.
static void init ()
This method is used to reset the static variables of the PlanarSeparator class.
static void BFSLayerGeneration (String initialState, MDP mdp)
This method creates BFS layers of the given MDP.
static void DFSDecomposition (String initialState, MDP mdp, long region)
This method creates DFS based decomposition of the given MDP.
static void DFSDecompositionIterative (String initialState, MDP mdp)
static Map< String, LinkedHashSet< String > > improveDecomposition (MDP mdp)
This method improves the basic DFS/BFS based decomposition of the given MDP.
Static Private Attributes
static HashSet< String > seenStates
static LinkedHashMap< String, LinkedHashSet< String > > layers
static int layerCount
Detailed Description
This class contains the source code for the BFS and DFS based MDP decomposition.
Definition at line 33 of file PlanarSeparator.java.
Member Function Documentation
static void mdp.util.PlanarSeparator.BFSLayerGeneration (String initialState, MDP mdp) [static]
This method creates BFS layers of the given MDP.
Note - This method is currently unused.
Definition at line 95 of file PlanarSeparator.java.
References mdp.core.MDP.getStates(), and mdp.util.PlanarSeparator.init().
static void mdp.util.PlanarSeparator.DFSDecomposition (String initialState, MDP mdp, long region) [static]
This method creates DFS based decomposition of the given MDP.
This method creates a decomposition by using a count based heuristic. Starting from the supplied initial State Label, the method places each newly discovered State into the current Region.
 When the State count inthe current region exceeds the total of Vertex Count / Region Count, then the Region count is incremented.
 This process is continued till all the states are explored via DFS and placed in a region. The final decomposition is placed in the Layers.
Definition at line 144 of file PlanarSeparator.java.
References mdp.core.State.getNextStates(), mdp.core.MDP.getRegionCount(), mdp.core.MDP.getStates(), mdp.core.State.setKernelLabel(), and mdp.core.State.setRegionLabel().
static void mdp.util.PlanarSeparator.DFSDecompositionIterative (String initialState, MDP mdp) [static]
Definition at line 187 of file PlanarSeparator.java.
References mdp.core.State.getLabel(), mdp.core.State.getNextStates(), mdp.core.MDP.getRegionCount(), mdp.core.MDP.getStates(), mdp.core.State.setKernelLabel(), and mdp.core.State.setRegionLabel().
Referenced by mdp.core.MDP.buildFromFile().
static int mdp.util.PlanarSeparator.getLayerCount () [static]
This method is a getter for the Layer Count.
Definition at line 70 of file PlanarSeparator.java.
References mdp.util.PlanarSeparator.layerCount.
static LinkedHashMap<String, LinkedHashSet<String> > mdp.util.PlanarSeparator.getLayers () [static]
This method is a getter for the Layers HashMap that returns the resultant decompositon.
Definition at line 56 of file PlanarSeparator.java.
References mdp.util.PlanarSeparator.layers.
Referenced by mdp.core.MDP.buildFromFile().
static HashSet<String> mdp.util.PlanarSeparator.getSeenStates () [static]
This method is a getter for the seenState HashMap.
Definition at line 42 of file PlanarSeparator.java.
References mdp.util.PlanarSeparator.seenStates.
static Map<String, LinkedHashSet<String> > mdp.util.PlanarSeparator.improveDecomposition (MDP mdp) [static]
This method improves the basic DFS/BFS based decomposition of the given MDP.
This method improves the decomposition by using an heuristic that a State should belong to the Region To and From which it has the maximum number of Transition.
 The method goes through each State in the nested Map that contains Key=State and Value=Map of {Key = Region and Value = Count of Transition to and From that Region to that State}
 Then the resultant Map is checked to return the Dominant Region of every State and if the State does not belong to that Region then its Region is changed to that Region. Finally the resultant decomposition is returned to the calling method.
Definition at line 241 of file PlanarSeparator.java.
References mdp.core.State.getLabel(), mdp.core.State.getRegionLabel(), mdp.core.MDP.getRegions(), mdp.core.MDP.getStates(), and mdp.core.State.getTransitions().
Referenced by mdp.core.MDP.buildFromFile().
static void mdp.util.PlanarSeparator.init () [static]
This method is used to reset the static variables of the PlanarSeparator class.
Definition at line 84 of file PlanarSeparator.java.
Referenced by mdp.util.PlanarSeparator.BFSLayerGeneration(), and mdp.core.MDP.buildFromFile().
static void mdp.util.PlanarSeparator.setLayerCount (int layerCount) [static]
This method is a setter for the Layer Count.
Definition at line 77 of file PlanarSeparator.java.
References mdp.util.PlanarSeparator.layerCount.
static void mdp.util.PlanarSeparator.setLayers (LinkedHashMap< String, LinkedHashSet< String >> layers) [static]
This method is a setter for the Layers HashMap.
Definition at line 63 of file PlanarSeparator.java.
References mdp.util.PlanarSeparator.layers.
static void mdp.util.PlanarSeparator.setSeenStates (HashSet< String > seenStates) [static]
This method is a setter for the seenState HashMap.
Definition at line 49 of file PlanarSeparator.java.
References mdp.util.PlanarSeparator.seenStates.
Member Data Documentation
int mdp.util.PlanarSeparator.layerCount [static], [private]
Definition at line 37 of file PlanarSeparator.java.
Referenced by mdp.util.PlanarSeparator.getLayerCount(), and mdp.util.PlanarSeparator.setLayerCount().
LinkedHashMap<String, LinkedHashSet<String> > mdp.util.PlanarSeparator.layers [static], [private]
Definition at line 36 of file PlanarSeparator.java.
Referenced by mdp.util.PlanarSeparator.getLayers(), and mdp.util.PlanarSeparator.setLayers().
HashSet<String> mdp.util.PlanarSeparator.seenStates [static], [private]
Definition at line 35 of file PlanarSeparator.java.
Referenced by mdp.util.PlanarSeparator.getSeenStates(), and mdp.util.PlanarSeparator.setSeenStates().
The documentation for this class was generated from the following file:
src/mdp/util/PlanarSeparator.java