ese.seas.upenn.edu.Main Class Reference
This class is used to create an MDP object from a text file and create a decomposition within that object and output the results i a .Mat file.
Static Public Member Functions
static void main (String[] args)
This method is used to create an MDP object from a text file and create a decomposition within that object and output the results i a .Mat file.
Detailed Description
This class is used to create an MDP object from a text file and create a decomposition within that object and output the results i a .Mat file.
Definition at line 41 of file Main.java.
Member Function Documentation
static void ese.seas.upenn.edu.Main.main (String[] args) [static]
This method is used to create an MDP object from a text file and create a decomposition within that object and output the results i a .Mat file.
Definition at line 49 of file Main.java.
References ese.seas.upenn.edu.MDP.buildFromFile(), ese.seas.upenn.edu.MDP.createSparseAMatrix(), and ese.seas.upenn.edu.MDP.getA().
The documentation for this class was generated from the following file:
src/ese/seas/upenn/edu/Main.java